name: filterz
description: An exploration of camera filters

publish_to: "none"

version: 0.0.1+alpha1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # extensions & utilities
  dartx: ^1.0.0
  camera: ^0.9.4+5

  # ui & themeing
  flutter_vector_icons: ^1.0.0
  google_fonts: ^2.2.0
  sliding_up_panel: ^2.0.0+1
  animated_text_kit: ^4.2.1
  flex_color_scheme: ^4.1.1

  # state management
  flutter_hooks: ^0.18.2
  flutter_state_notifier: ^0.7.1
  freezed_annotation: ^1.1.0
  hooks_riverpod: ^1.0.3
  json_annotation: ^4.4.0
  state_notifier: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.7
  dependency_validator: ^3.1.2
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^1.0.4
  flutter_native_splash: ^1.3.3
  freezed: ^1.1.1
  import_sorter: ^4.6.0
  json_serializable: ^6.1.3
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
